// <auto-generated />
using HotelAPI.MyAppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240224134520_AddedCityAndCountryInHotels")]
    partial class AddedCityAndCountryInHotels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HotelAPI.Models.Hotel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = "076fb610-1bac-4fc3-95ce-209d3f8f4d19",
                            City = "Los Angeles",
                            Country = "United States of America",
                            Name = "Hills"
                        },
                        new
                        {
                            Id = "13f63e52-4837-4b24-931e-504328060ac8",
                            City = "Sofia",
                            Country = "Bulgaria",
                            Name = "Sofia"
                        },
                        new
                        {
                            Id = "62d06c84-668d-4840-b749-02200592909d",
                            City = "Mexico",
                            Country = "Mexico",
                            Name = "Nexus"
                        },
                        new
                        {
                            Id = "0a1450be-63db-4b04-9ea9-203c1fc60b97",
                            City = "Nessebar",
                            Country = "Bulgaria",
                            Name = "Nessebar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
